baseurl = "https://example.com/"
languageCode = "en-us"
theme = "terminal"
Paginate = 3

[params]
  contentTypeName = "post"
  themeColor = "orange"
  showMenuItems = 4
  fullWidthTheme = false
  centerTheme = true
  showLanguageSelector = true
  showFullContent = true
  github = "https://github.com/alariq/mc2"

  featured_image = "/images/title.jpg"

[languages]
  [languages.en]
    title = "Mech Commander2 HD"
    subtitle = "An OpenGL Linux port of an old classic"
    keywords = "mech commander 2 linux games opengl"
    copyright = ""
    menuMore = "Show more"
    readMore = "Read more"
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "Mech Commander2 HD"
      logoHomeLink = "/"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "about"
        name = "About"
        url = "/about"
      [[languages.en.menu.main]]
        identifier = "blog"
        name = "Blog"
        url = "/blog/"
      [[languages.en.menu.main]]
        identifier = "post"
        name = "Posts"
        url = "/post/"
